Project work. Sprint 2 part 2
Moralex45/stellar-burger pull request #2
Opened 2023-03-24 14:43 UTC by Moralex45

2023-03-24 15:21 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/1XGdv_ZMjgK5ZQ> - не хватает иконки;

- В компоненте App-header требуется поправить семантику, переделать button в ссылки. Не стоит оборачивать кнопки в ссылку, это не очень корректно;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/xJK0HlzfWiiLEg>;

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-03-24 15:21 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +        const ingredientsId = [...ingredients.map((item) => item._id), bun._id];
**Надо исправить:**

В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива.

2023-03-24 15:21 UTC, ArslanDev666 commented on src/index.js
> +const store = createStore(rootReducer, enhancer);
**Можно лучше:**

лучше перенести это всё в папку `services`, и создать там файлик `store.js`.

2023-03-24 15:21 UTC, ArslanDev666 commented on src/services/reducers/ingredientsReducer.js
> +    totalPrice: 0,
**Можно лучше**

Хотя в задании и предложено вычислять полную стоимость в редьюсере, но это плохая идея, т.к. общая стоимость это производные данные от данных о бургере и сейчас у нас в некотором роде дублируется эта информация (есть массив ингредиентов с ценами и есть отдельно полная стоимость)

Поэтому лучше рассчитывать их не в редьюсере а просто в компоненте конструктора используя useMemo

```js
const totalPrice = useMemo(()=> {
   return **рассчет стоимости**
}, burgersData)
```

так стоимость будет перерасчитываться в момент изменения бургера

Можно и без `useMemo`)

2023-03-24 15:21 UTC, ArslanDev666 commented on src/services/reducers/ingredientsReducer.js
> +    addedBun: [],
**Можно лучше:**

тут лучше использовать объект булки, а не массив. У нас ведь одна булка.

2023-03-24 15:21 UTC, ArslanDev666 commented on src/utils/api.js
>  const checkIFResp = (response) => {
**Можно лучше:**

Лучше назвать это `checkResponse`, так будет более корректно.

2023-03-24 16:23 UTC, Moralex45 commented
Добрый день!
Спасибо за ревью! 

Все что под грифом "Надо исправить" - постарался исправить. Надеюсь, что правильно учел Ваши замечания.

Все улучшения "Можно сделать лучше" - исправлю в будущем спринте, боюсь не успеть в нынешнем, т.к. дедлайн в воскресенье ;)

2023-03-25 07:45 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но осталось ещё небольшое замечание, которые нужно исправить:**

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива. <https://disk.yandex.com/i/1T3wmBE2cg65uQ> - сейчас там не **id**, а объекты, и они идут подряд, а не в начале и в конце массива;

### **Сделает код лучше:**

- В компоненте App-header требуется поправить семантику, переделать button в ссылки. Не стоит оборачивать ссылку в кнопку (лучше вообще от кнопки избавится), это не очень корректно;

2023-03-25 07:45 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +        const ingredientsId = [bun, bun, ...ingredients.map((item) => item._id)];
**Надо исправить:**

нужно чтобы id у булок были в начале и в конце массива.

```js
const ingredientsId = [bun._id, ...ingredients.map((item) => item._id, bun._id)];
```

2023-03-25 09:17 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята. Удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-04-07 07:28 UTC, merged