Sprint 3/step 1
Moralex45/stellar-burger pull request #3
Opened 2023-04-11 09:53 UTC by Moralex45

2023-04-11 11:06 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализован механизм обновления токена
- Настроены все переадресации
- Реализована защита роутов
- Используется тег `form`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Если в куках нет токена, то и делать запрос на юзера нет смысла. Иначе это к тому же вызывает ненужное обновление токена. 

<img width="1438" alt="Снимок экрана 2023-04-11 в 13 48 53" src="https://user-images.githubusercontent.com/60173362/231138472-d9580dfd-5fce-484a-b6aa-fe26525b7d3f.png">

- Не стоит позволять юзеру делать заказа если в конструкторе ничего нет.
- Роут reset-password должен быть доступен только через роут `forgot-password`.
- Есть небольшой баг - при закрытии модального окна с заказом открывается страница профиля или страница с ингредиентом. Чтобы его воспроизвести надо сначала открыть и закрыть модальное окно с ингредиентом. 

https://user-images.githubusercontent.com/60173362/231139737-37346221-b445-47e2-9d7b-aa81499123de.mov

**Можно лучше**
- Чтобы приходящий с сервера токен заносился всегда по пути `"/"` в куку, нужно в функцию setCookies передавать как значение параметра props аргумент 
```
{path="/"}:
setCookie('name', value, { path: '/' })
```

Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-11 11:06 UTC, andryxxa93 commented on src/components/app/app.jsx
> +          <Route index element={<MainPage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-04-11 11:06 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const bun = useSelector((state) => state.ingredientReducer.addedBun);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-04-11 11:06 UTC, andryxxa93 commented on src/components/ingredients-card/ingredients-card.jsx
> +  [addedBun].forEach((bun) => bun._id === id ? (ingredientsCounter += 2) : ingredientsCounter);
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-04-11 11:06 UTC, andryxxa93 commented on src/components/protectedRouteElement/protectedRouteElement.jsx
> +export const ProtectedRouteElement = ({ element }) => {
**Можно лучше**
доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-04-11 11:06 UTC, andryxxa93 commented on src/pages/forgotPasswordPage/forgotPasswordPage.jsx
> +          <form className={style.form} onSubmit={(e) => handleResetPassword(e)}>
**Можно лучше**
Тут можно сократить и не создавать анонимную функцию - `onSubmit={handleResetPassword}`

2023-04-12 20:50 UTC, Moralex45 commented
Касательно бага с модальным окном, изначально смог воспроизвести. Затем нет, возможно каким-то образом само устаканилось в процессе исправления)

2023-04-13 12:22 UTC, andryxxa93 commented
> Касательно бага с модальным окном, изначально смог воспроизвести. Затем нет, возможно каким-то образом само устаканилось в процессе исправления)

Скорее всего дело в том, что вы используете previousLocation у объекта location. Следует использовать `background`.

2023-04-13 12:23 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-13 15:04 UTC, merged